# Generated by Django 5.2.8 on 2026-07-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_sim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_id', models.CharField(max_length=32)),
                ('vehicle_id', models.CharField(max_length=64)),
                ('asset_key', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=16)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sandbox_text_attempt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sandboxstate',
            name='scenario',
            field=models.CharField(choices=[('normal', '正常流程'), ('duplicate', '重复报警'), ('missing_fields', '字段缺失'), ('schema_changed', '响应结构变化'), ('unauthorized', '登录失效'), ('server_error', '服务异常'), ('slow', '慢响应'), ('intercom_failure', '对讲失败'), ('text_failure', '文本下发失败')], default='normal', max_length=32),
        ),
    ]
