# Generated by Django 5.2.8 on 2026-07-20 16:25

from django.conf import settings
from django.db import migrations, models


def deactivate_duplicate_active_platform_devices(apps, schema_editor):
    """Make existing SQLite/PostgreSQL data safe before adding the constraint.

    The newest heartbeat remains active; older duplicates require an explicit
    administrator rebind after deployment.
    """
    DeviceRegistration = apps.get_model("governance", "DeviceRegistration")
    seen = set()
    rows = DeviceRegistration.objects.filter(is_active=True).exclude(platform_account_ref="").order_by(
        "platform_account_ref", "-last_seen_at", "-id"
    )
    for row in rows:
        if row.platform_account_ref in seen:
            row.is_active = False
            row.save(update_fields=["is_active"])
        else:
            seen.add(row.platform_account_ref)


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_deviceregistration_sessionkeepaliveaudit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deactivate_duplicate_active_platform_devices, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='deviceregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('platform_account_ref__gt', '')), fields=('platform_account_ref',), name='unique_active_platform_device'),
        ),
    ]
