# Generated by Django 5.2.8 on 2026-07-20 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0007_deviceregistration_platform_display_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceInteractionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='PROVINCIAL_PLATFORM_VOICE', editable=False, max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('record_driver_audio', models.BooleanField(default=False)),
                ('transcribe_driver_audio', models.BooleanField(default=False)),
                ('consent_required', models.BooleanField(default=True, editable=False)),
                ('retention_days', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_voice_interaction_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_voice_interaction_policies',
            },
        ),
    ]
