# Generated by Django 5.2.8 on 2026-07-19 07:25

import apps.governance.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposals', '0001_create_disposal_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposalcase',
            name='decision_snapshot',
            field=apps.governance.encrypted_fields.EncryptedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='disposalcase',
            name='event_snapshot',
            field=apps.governance.encrypted_fields.EncryptedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='disposalcase',
            name='latest_event_snapshot',
            field=apps.governance.encrypted_fields.EncryptedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='disposalevent',
            name='detail',
            field=apps.governance.encrypted_fields.EncryptedJSONField(default=dict),
        ),
    ]
