# Generated by Django 5.2.8 on 2026-07-19 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0003_unique_active_platform_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_id', models.CharField(max_length=160, unique=True)),
                ('alarm_id', models.CharField(blank=True, default='', max_length=160)),
                ('source_kind', models.CharField(db_index=True, max_length=30)),
                ('alarm_name', models.CharField(blank=True, default='', max_length=200)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=100)),
                ('event_snapshot', models.JSONField(default=dict)),
                ('latest_event_snapshot', models.JSONField(default=dict)),
                ('decision_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('MANUAL_REQUIRED', '待人工接管'), ('IN_MANUAL', '人工处理中'), ('PENDING_REVIEW', '待复核'), ('COMPLETED', '已完成'), ('REOPENED', '已重开')], db_index=True, default='MANUAL_REQUIRED', max_length=30)),
                ('requires_review', models.BooleanField(default=True)),
                ('taken_over_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_code', models.CharField(blank=True, default='', max_length=80)),
                ('resolution_note', models.CharField(blank=True, default='', max_length=1000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.CharField(blank=True, default='', max_length=1000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_disposal_cases', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_disposal_cases', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_cases', to='governance.enterprisescope')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_disposal_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_disposal_cases',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DisposalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('CREATED', '已创建'), ('SNAPSHOT_UPDATED', '快照已更新'), ('TAKEN_OVER', '已接管'), ('NOTE_ADDED', '已备注'), ('SUBMITTED_REVIEW', '已提交复核'), ('COMPLETED', '已完成'), ('REVIEW_APPROVED', '复核通过'), ('REVIEW_REJECTED', '复核退回'), ('REOPENED', '已重开')], db_index=True, max_length=30)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(blank=True, default='', max_length=30)),
                ('comment', models.CharField(blank=True, default='', max_length=1000)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_events', to=settings.AUTH_USER_MODEL)),
                ('disposal_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='disposals.disposalcase')),
            ],
            options={
                'db_table': 'assistant_disposal_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='disposalcase',
            index=models.Index(fields=['enterprise', 'status', '-updated_at'], name='disposal_scope_status_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalcase',
            index=models.Index(fields=['assigned_to', 'status'], name='disposal_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalevent',
            index=models.Index(fields=['disposal_case', 'created_at'], name='disposal_event_case_time_idx'),
        ),
    ]
