# Generated by Django 5.2.8 on 2026-07-20 02:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_consolidate_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_id', models.CharField(max_length=120, unique=True)),
                ('platform_account_ref', models.CharField(blank=True, default='', max_length=120)),
                ('extension_version', models.CharField(blank=True, default='', max_length=40)),
                ('session_status', models.CharField(blank=True, default='UNKNOWN', max_length=40)),
                ('last_route', models.CharField(blank=True, default='', max_length=200)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_device_registrations',
            },
        ),
        migrations.CreateModel(
            name='SessionKeepaliveAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('policy_version', models.PositiveIntegerField()),
                ('route', models.CharField(blank=True, default='', max_length=200)),
                ('result_code', models.CharField(db_index=True, max_length=40)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('attempted_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_keepalive_audits', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keepalive_audits', to='governance.deviceregistration')),
            ],
            options={
                'db_table': 'assistant_session_keepalive_audits',
            },
        ),
        migrations.CreateModel(
            name='SessionKeepalivePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='PROVINCIAL_PLATFORM', editable=False, max_length=40, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('interval_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(50)])),
                ('target_route', models.CharField(default='#/alarm-center/alarm-preprocessing', editable=False, max_length=160)),
                ('target_action_key', models.CharField(default='ALARM_PREPROCESSING_QUERY', editable=False, max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_session_keepalive_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_session_keepalive_policies',
            },
        ),
        migrations.AddIndex(
            model_name='deviceregistration',
            index=models.Index(fields=['user', 'is_active', '-last_seen_at'], name='assistant_device_user_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionkeepaliveaudit',
            index=models.Index(fields=['device', '-attempted_at'], name='assistant_keepalive_device_idx'),
        ),
    ]
