# Generated by Django 5.2.8 on 2026-07-20 16:58

import apps.governance.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0006_enforce_one_device_per_platform_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceregistration',
            name='platform_display_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='platform_identity_observed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='platform_identity_status',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='platform_permission_summary',
            field=apps.governance.encrypted_fields.EncryptedJSONField(default=dict),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='platform_visible_scope_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
