# Generated by Django 5.2.8 on 2026-07-19 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0003_unique_active_platform_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('asset_key', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('TEXT', '固定文本'), ('VOICE', '固定语音')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('IN_REVIEW', '审核中'), ('APPROVED', '已批准'), ('REJECTED', '已驳回'), ('PUBLISHED', '已发布'), ('RETIRED', '已退役')], db_index=True, default='DRAFT', max_length=20)),
                ('text_template', models.TextField(blank=True, default='')),
                ('voice_bytes', models.BinaryField(blank=True, default=bytes)),
                ('voice_filename', models.CharField(blank=True, default='', max_length=255)),
                ('voice_mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('channels', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bits_per_sample', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('change_note', models.CharField(max_length=500)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.CharField(blank=True, default='', max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_assets', to='response_governance.responseasset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_response_assets', to=settings.AUTH_USER_MODEL)),
                ('enterprise_scopes', models.ManyToManyField(related_name='response_assets', to='governance.enterprisescope')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_response_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_response_assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseAssetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('CREATED', '已创建'), ('UPDATED', '已更新'), ('SUBMITTED', '已提交'), ('APPROVED', '已批准'), ('REJECTED', '已驳回'), ('PUBLISHED', '已发布'), ('RETIRED', '已退役')], db_index=True, max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=1000)),
                ('content_hash_snapshot', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_asset_events', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='response_governance.responseasset')),
            ],
            options={
                'db_table': 'assistant_response_asset_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='responseasset',
            index=models.Index(fields=['channel_type', 'status', '-created_at'], name='response_asset_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='responseasset',
            index=models.Index(fields=['asset_key', 'status'], name='response_asset_key_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='responseasset',
            constraint=models.UniqueConstraint(fields=('asset_key', 'version'), name='unique_response_asset_version'),
        ),
        migrations.AddConstraint(
            model_name='responseasset',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('asset_key', 'channel_type'), name='unique_published_response_asset'),
        ),
        migrations.AddIndex(
            model_name='responseassetevent',
            index=models.Index(fields=['asset', 'created_at'], name='response_asset_event_time_idx'),
        ),
    ]
