# Generated by Django 5.2.8 on 2026-07-19 07:25

import apps.governance.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_create_report_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmfact',
            name='action_snapshot',
            field=apps.governance.encrypted_fields.EncryptedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='alarmfact',
            name='decision_snapshot',
            field=apps.governance.encrypted_fields.EncryptedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='alarmfact',
            name='event_snapshot',
            field=apps.governance.encrypted_fields.EncryptedJSONField(default=dict),
        ),
    ]
