# Generated by Django 5.2.8 on 2026-07-20 16:58

import apps.governance.encrypted_fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0007_deviceregistration_platform_display_name_and_more'),
        ('reporting', '0006_reclassify_preprocessing_as_pending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlease',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionlease',
            name='lease_token_hash',
            field=models.CharField(blank=True, default='', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='actionlease',
            name='result_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='actionlease',
            name='result_payload',
            field=apps.governance.encrypted_fields.EncryptedJSONField(default=dict),
        ),
        migrations.AddField(
            model_name='actionlease',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionlease',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '有效'), ('EXECUTING', '执行中'), ('COMPLETED', '已完成'), ('FAILED', '明确失败'), ('BLOCKED', '被阻断'), ('MANUAL_REQUIRED', '转人工'), ('EXPIRED', '已过期'), ('UNKNOWN', '结果未知')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='DutyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_id', models.CharField(db_index=True, max_length=160)),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('result_code', models.CharField(blank=True, default='', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=1000)),
                ('detail', apps.governance.encrypted_fields.EncryptedJSONField(default=dict)),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('UNREAD', '未读'), ('ACKNOWLEDGED', '已确认')], db_index=True, default='UNREAD', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_duty_notifications', to=settings.AUTH_USER_MODEL)),
                ('action_lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='reporting.actionlease')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_notifications', to='governance.enterprisescope')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_duty_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status', '-created_at'], name='duty_notice_recipient_idx'), models.Index(fields=['enterprise', 'event_id', '-created_at'], name='duty_notice_event_idx')],
            },
        ),
    ]
