# Generated by Django 5.2.8 on 2026-07-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_actionlease_last_attempt_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlease',
            name='lease_token_hash',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
