# Generated by Django 5.2.8 on 2026-07-20 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_alter_actionlease_lease_token_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actionlease',
            name='unique_active_fact_action_lease',
        ),
        migrations.AddConstraint(
            model_name='actionlease',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'EXECUTING'])), fields=('fact', 'action_type'), name='unique_active_fact_action_lease'),
        ),
    ]
