# Generated by Django 5.2.8 on 2026-07-20 17:31

import apps.governance.encrypted_fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0008_voiceinteractionpolicy'),
        ('reporting', '0009_remove_actionlease_unique_active_fact_action_lease_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceInteractionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_id', models.CharField(db_index=True, max_length=160)),
                ('policy_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('CAPTURED', '已登记录音'), ('TRANSCRIBED', '已转文字'), ('FAILED', '处理失败'), ('EXPIRED', '已过期')], db_index=True, default='CAPTURED', max_length=20)),
                ('transcription_status', models.CharField(choices=[('NOT_REQUESTED', '未请求转写'), ('PENDING', '等待转写'), ('READY', '转写完成'), ('FAILED', '转写失败')], db_index=True, default='NOT_REQUESTED', max_length=20)),
                ('audio_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('audio_duration_ms', models.PositiveIntegerField(default=0)),
                ('audio_metadata', apps.governance.encrypted_fields.EncryptedJSONField(default=dict)),
                ('transcript', apps.governance.encrypted_fields.EncryptedJSONField(default=dict)),
                ('transcript_engine', models.CharField(blank=True, default='', max_length=80)),
                ('transcript_confidence', models.FloatField(blank=True, null=True)),
                ('recorded_started_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_ended_at', models.DateTimeField(blank=True, null=True)),
                ('retention_until', models.DateTimeField(db_index=True)),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
                ('action_lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voice_evidence', to='reporting.actionlease')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_interaction_evidence', to='governance.enterprisescope')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_evidence', to='reporting.alarmfact')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_voice_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_voice_interaction_evidence',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enterprise', 'status', '-created_at'], name='voice_evidence_scope_idx'), models.Index(fields=['retention_until', 'status'], name='voice_evidence_retention_idx')],
            },
        ),
    ]
