# Generated by Django 5.2.8 on 2026-07-22 17:57

import apps.governance.encrypted_fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0010_enterprisescope_allow_platform_discovery'),
        ('reporting', '0012_plan_level_action_lease'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSourceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(db_index=True, max_length=50)),
                ('contract_version', models.CharField(max_length=80)),
                ('query_hash', models.CharField(max_length=64)),
                ('field_signature', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', '等待取数'), ('FETCHING', '取数中'), ('COMPLETE', '已完成'), ('INVALID', '不完整')], db_index=True, default='PENDING', max_length=20)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('received_pages', models.PositiveIntegerField(default=0)),
                ('received_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('anomaly_rows', models.PositiveIntegerField(default=0)),
                ('filters_summary', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assistant_report_source_batches',
            },
        ),
        migrations.CreateModel(
            name='ReportSourcePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(max_length=50)),
                ('page_number', models.PositiveIntegerField()),
                ('query_hash', models.CharField(max_length=64)),
                ('field_signature', models.CharField(max_length=64)),
                ('row_count', models.PositiveIntegerField()),
                ('page_hash', models.CharField(max_length=64)),
                ('rows', apps.governance.encrypted_fields.EncryptedJSONField(default=list)),
            ],
            options={
                'db_table': 'assistant_report_source_pages',
            },
        ),
        migrations.CreateModel(
            name='ReportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_type', models.CharField(choices=[('ALARM_DAILY', '企业报警日报'), ('ALARM_WEEKLY', '企业报警周报'), ('ALARM_MONTHLY', '企业报警月报'), ('VEHICLE_MONITOR_DAILY', '车辆动态监控日报')], db_index=True, max_length=40)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('template_version', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('CREATED', '已创建'), ('WAITING_PLATFORM', '等待省平台'), ('FETCHING', '取数中'), ('VALIDATING', '校验中'), ('REVIEW_REQUIRED', '待审核'), ('APPROVED', '已审核'), ('DATA_INCOMPLETE', '数据不完整'), ('REJECTED', '已驳回'), ('FAILED', '失败')], db_index=True, default='CREATED', max_length=30)),
                ('query_spec', apps.governance.encrypted_fields.EncryptedJSONField(default=dict)),
                ('required_source_types', models.JSONField(default=list)),
                ('validation_summary', apps.governance.encrypted_fields.EncryptedJSONField(default=dict)),
                ('failure_code', models.CharField(blank=True, default='', max_length=80)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=1000)),
                ('critical_issue_count', models.PositiveIntegerField(default=0)),
                ('data_cutoff_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, default='', max_length=1000)),
                ('platform_account_ref', models.CharField(blank=True, default='', max_length=120)),
                ('device_id', models.CharField(blank=True, default='', max_length=120)),
                ('lease_token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'assistant_report_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMonitorDailyRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('vehicle_key_hash', models.CharField(db_index=True, max_length=64)),
                ('row_kind', models.CharField(choices=[('FORMAL', '正式日报'), ('FILTERED', '过滤清单'), ('ANOMALY', '异常清单')], db_index=True, max_length=20)),
                ('online_status', models.CharField(blank=True, default='', max_length=40)),
                ('trajectory_status', models.CharField(blank=True, default='', max_length=60)),
                ('filter_reason', models.CharField(blank=True, default='', max_length=200)),
                ('anomaly_reason', models.CharField(blank=True, default='', max_length=500)),
                ('critical', models.BooleanField(db_index=True, default=False)),
                ('data', apps.governance.encrypted_fields.EncryptedJSONField(default=dict)),
            ],
            options={
                'db_table': 'assistant_vehicle_monitor_daily_rows',
            },
        ),
        migrations.RemoveConstraint(
            model_name='reportsnapshot',
            name='unique_report_snapshot_version',
        ),
        migrations.RemoveConstraint(
            model_name='reportsnapshot',
            name='unique_published_report_period',
        ),
        migrations.RemoveIndex(
            model_name='reportsnapshot',
            name='report_scope_period_idx',
        ),
        migrations.AddField(
            model_name='reportsnapshot',
            name='report_type',
            field=models.CharField(db_index=True, default='LEGACY_OPERATIONAL', max_length=40),
        ),
        migrations.AddField(
            model_name='reportsnapshot',
            name='review_status',
            field=models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已审核'), ('REJECTED', '已驳回')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='reportsnapshot',
            name='template_version',
            field=models.CharField(default='LEGACY_V1', max_length=80),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='format',
            field=models.CharField(choices=[('XLSX', 'Excel'), ('PDF', 'PDF'), ('ZIP', '批量压缩包')], max_length=10),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='report_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to='reporting.reportsnapshot'),
        ),
        migrations.AlterField(
            model_name='reportsnapshot',
            name='period_type',
            field=models.CharField(choices=[('DAILY', '日报'), ('WEEKLY', '周报'), ('MONTHLY', '月报')], max_length=10),
        ),
        migrations.AddField(
            model_name='reportsourcepage',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='reporting.reportsourcebatch'),
        ),
        migrations.AddField(
            model_name='reporttask',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_report_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttask',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_report_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttask',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_report_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportsourcepage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_pages', to='reporting.reporttask'),
        ),
        migrations.AddField(
            model_name='reportsourcebatch',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_batches', to='reporting.reporttask'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='report_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to='reporting.reporttask'),
        ),
        migrations.AddField(
            model_name='reportsnapshot',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='reporting.reporttask'),
        ),
        migrations.AddIndex(
            model_name='reportsnapshot',
            index=models.Index(fields=['enterprise', 'report_type', '-period_start'], name='report_scope_type_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('report_snapshot__isnull', False), ('report_task__isnull', True)), models.Q(('report_snapshot__isnull', True), ('report_task__isnull', False)), _connector='OR'), name='export_exactly_one_report_target'),
        ),
        migrations.AddConstraint(
            model_name='reportsnapshot',
            constraint=models.UniqueConstraint(fields=('enterprise', 'report_type', 'period_type', 'period_start', 'version'), name='unique_report_snapshot_version_v2'),
        ),
        migrations.AddConstraint(
            model_name='reportsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('enterprise', 'report_type', 'period_type', 'period_start'), name='unique_published_report_period_v2'),
        ),
        migrations.AddField(
            model_name='vehiclemonitordailyrow',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_daily_rows', to='governance.enterprisescope'),
        ),
        migrations.AddField(
            model_name='vehiclemonitordailyrow',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_daily_rows', to='reporting.reportsnapshot'),
        ),
        migrations.AddField(
            model_name='vehiclemonitordailyrow',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_daily_rows', to='reporting.reporttask'),
        ),
        migrations.AddField(
            model_name='vehiclemonitordailyrow',
            name='trajectory_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_daily_trajectory_rows', to='reporting.reportsourcebatch'),
        ),
        migrations.AddField(
            model_name='vehiclemonitordailyrow',
            name='vehicle_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_daily_base_rows', to='reporting.reportsourcebatch'),
        ),
        migrations.AddIndex(
            model_name='reporttask',
            index=models.Index(fields=['status', '-created_at'], name='report_task_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsourcepage',
            index=models.Index(fields=['batch', 'page_number'], name='report_page_batch_number_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportsourcepage',
            constraint=models.UniqueConstraint(fields=('task', 'source_type', 'page_number', 'query_hash'), name='unique_report_source_page'),
        ),
        migrations.AddIndex(
            model_name='reportsourcebatch',
            index=models.Index(fields=['task', 'status'], name='report_batch_task_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportsourcebatch',
            constraint=models.UniqueConstraint(fields=('task', 'source_type'), name='unique_task_report_source'),
        ),
        migrations.AddIndex(
            model_name='vehiclemonitordailyrow',
            index=models.Index(fields=['task', 'row_kind', 'enterprise'], name='vehicle_daily_task_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemonitordailyrow',
            constraint=models.UniqueConstraint(fields=('task', 'row_number'), name='unique_task_vehicle_daily_row'),
        ),
    ]
