# Generated by Django 5.2.8 on 2026-07-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0013_reportsourcebatch_reportsourcepage_reporttask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmfact',
            name='processing_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarmfact',
            name='processing_source',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='alarmfact',
            name='processing_status',
            field=models.CharField(choices=[('UNPROCESSED', '未处理'), ('EXECUTING', '处理中'), ('PROCESSED', '已处理'), ('MANUAL_REQUIRED', '待人工处理'), ('UNKNOWN', '处理结果未知')], db_index=True, default='UNPROCESSED', max_length=30),
        ),
    ]
