# Generated by Django 5.2.8 on 2026-07-19 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0003_unique_active_platform_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('period_type', models.CharField(choices=[('DAILY', '日报'), ('MONTHLY', '月报')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('RETIRED', '已退役')], db_index=True, default='DRAFT', max_length=20)),
                ('metrics', models.JSONField(default=dict)),
                ('parameters', models.JSONField(default=dict)),
                ('data_cutoff_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('correction_reason', models.CharField(blank=True, default='', max_length=1000)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_snapshots', to='governance.enterprisescope')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_report_snapshots',
                'ordering': ['-period_start', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('format', models.CharField(choices=[('XLSX', 'Excel'), ('PDF', 'PDF')], max_length=10)),
                ('status', models.CharField(choices=[('READY', '可下载'), ('EXPIRED', '已过期'), ('DELETED', '已删除')], db_index=True, default='READY', max_length=20)),
                ('purpose', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_sha256', models.CharField(max_length=64)),
                ('file_size', models.PositiveBigIntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
                ('report_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to='reporting.reportsnapshot')),
            ],
            options={
                'db_table': 'assistant_export_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlarmFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=160, unique=True)),
                ('alarm_id', models.CharField(blank=True, default='', max_length=160)),
                ('company_name_snapshot', models.CharField(max_length=200)),
                ('source_kind', models.CharField(db_index=True, max_length=30)),
                ('alarm_name', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('alarm_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('vehicle_id', models.CharField(blank=True, default='', max_length=160)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=100)),
                ('final_state', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('event_snapshot', models.JSONField(default=dict)),
                ('decision_snapshot', models.JSONField(default=dict)),
                ('action_snapshot', models.JSONField(default=dict)),
                ('first_seen_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarm_facts', to='governance.enterprisescope')),
                ('ingested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingested_alarm_facts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_alarm_facts',
                'ordering': ['-alarm_time', '-last_seen_at'],
                'indexes': [models.Index(fields=['enterprise', 'alarm_time'], name='alarm_fact_scope_time_idx'), models.Index(fields=['enterprise', 'source_kind', 'alarm_time'], name='alarm_fact_source_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reportsnapshot',
            index=models.Index(fields=['enterprise', 'period_type', '-period_start'], name='report_scope_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportsnapshot',
            constraint=models.UniqueConstraint(fields=('enterprise', 'period_type', 'period_start', 'version'), name='unique_report_snapshot_version'),
        ),
        migrations.AddConstraint(
            model_name='reportsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('enterprise', 'period_type', 'period_start'), name='unique_published_report_period'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['created_by', 'status', '-created_at'], name='export_user_status_idx'),
        ),
    ]
