# Generated by Django 5.2.8 on 2026-07-20 02:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_deviceregistration_sessionkeepaliveaudit_and_more'),
        ('reporting', '0004_alarm_fact_ingestion_provenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_id', models.CharField(max_length=120)),
                ('action_type', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('COMPLETED', '已完成'), ('EXPIRED', '已过期'), ('UNKNOWN', '结果未知')], db_index=True, default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assistant_action_leases',
            },
        ),
        migrations.CreateModel(
            name='CaptureSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_id', models.CharField(max_length=160)),
                ('device_id', models.CharField(max_length=120)),
                ('platform_account_ref', models.CharField(max_length=120)),
                ('extension_version', models.CharField(blank=True, default='', max_length=40)),
                ('endpoint', models.CharField(blank=True, default='', max_length=300)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assistant_alarm_capture_sources',
            },
        ),
        migrations.AddField(
            model_name='alarmfact',
            name='business_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='alarmfact',
            index=models.Index(fields=['source_kind', 'final_state', '-last_seen_at'], name='alarm_fact_state_seen_idx'),
        ),
        migrations.AddField(
            model_name='actionlease',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarm_action_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionlease',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_leases', to='reporting.alarmfact'),
        ),
        migrations.AddField(
            model_name='capturesource',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_sources', to='reporting.alarmfact'),
        ),
        migrations.AddField(
            model_name='capturesource',
            name='ingested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarm_capture_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='actionlease',
            index=models.Index(fields=['status', 'expires_at'], name='action_lease_status_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='actionlease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('fact', 'action_type'), name='unique_active_fact_action_lease'),
        ),
        migrations.AddIndex(
            model_name='capturesource',
            index=models.Index(fields=['fact', '-captured_at'], name='alarm_capture_fact_time_idx'),
        ),
        migrations.AddIndex(
            model_name='capturesource',
            index=models.Index(fields=['device_id', '-captured_at'], name='alarm_capture_device_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='capturesource',
            constraint=models.UniqueConstraint(fields=('device_id', 'capture_id'), name='unique_device_capture'),
        ),
    ]
