# Generated by Django 5.2.8 on 2026-07-22 19:24

from django.conf import settings
from django.db import migrations, models


def quarantine_preexisting_active_leases(apps, schema_editor):
    ActionLease = apps.get_model('reporting', 'ActionLease')
    AlarmFact = apps.get_model('reporting', 'AlarmFact')
    fact_ids = list(ActionLease.objects.filter(status__in=['ACTIVE', 'EXECUTING']).values_list('fact_id', flat=True))
    ActionLease.objects.filter(status__in=['ACTIVE', 'EXECUTING']).update(
        status='UNKNOWN', result_code='MIGRATION_SCOPE_UNKNOWN'
    )
    AlarmFact.objects.filter(pk__in=fact_ids).update(
        processing_status='UNKNOWN', processing_source='MIGRATION_SCOPE_QUARANTINE'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0014_alarmfact_processing_marked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlease',
            name='action_scope_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='actionlease',
            index=models.Index(fields=['action_scope_key', '-created_at'], name='action_scope_recent_idx'),
        ),
        migrations.RunPython(quarantine_preexisting_active_leases, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='actionlease',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'EXECUTING']), models.Q(('action_scope_key', ''), _negated=True)), fields=('action_scope_key',), name='unique_active_vehicle_alarm_scope'),
        ),
    ]
