# Generated by Django 5.2.8 on 2026-07-19 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_unique_active_platform_account'),
        ('response_governance', '0001_create_response_asset_governance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='responseasset',
            name='unique_published_response_asset',
        ),
        migrations.AddConstraint(
            model_name='responseasset',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('asset_key',), name='unique_published_response_asset_key'),
        ),
    ]
