# Generated by Django 5.2.8 on 2026-07-19 07:33

import apps.governance.encrypted_fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0003_unique_active_platform_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(max_length=500)),
                ('event_ids', apps.governance.encrypted_fields.EncryptedJSONField(default=list)),
                ('requested_fields', apps.governance.encrypted_fields.EncryptedJSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', '待审批'), ('REJECTED', '已驳回'), ('READY', '加密包可下载'), ('EXPIRED', '已过期'), ('DELETED', '已删除')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.CharField(blank=True, default='', max_length=1000)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('file_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('encryption_algorithm', models.CharField(blank=True, default='', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_requests', to='governance.enterprisescope')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_evidence_packages', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_evidence_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_evidence_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enterprise', 'status', '-created_at'], name='evidence_scope_status_idx'), models.Index(fields=['requested_by', 'status'], name='evidence_requester_status_idx')],
            },
        ),
    ]
